service: biwenger-client
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-1
  stage: production
  environment:
    BIWENGER_EMAIL: ${env:BIWENGER_EMAIL}
    BIWENGER_PASSWORD: ${env:BIWENGER_PASSWORD}
  apiGateway:
    apiKeys:
      - name: biwenger-client-${self:provider.stage}-mobile-key
        value: ${env:BIWENGER_CLIENT_MOBILE_API_KEY}
    usagePlan: {}

functions:
  squad:
    handler: src/index.squad
    events:
      - http:
          method: GET
          path: /squad
          private: true
  priceHistory:
    handler: src/index.priceHistory
    events:
      - http:
          method: GET
          path: /players/{playerId}/price-history
          private: true
