service: biwenger-client
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-1
  stage: production
  environment:
    BIWENGER_EMAIL: ${env:BIWENGER_EMAIL}
    BIWENGER_PASSWORD: ${env:BIWENGER_PASSWORD}
  apiGateway:
    apiKeys:
      - name: biwenger-client-${self:provider.stage}-mobile-key
        value: ${env:BIWENGER_CLIENT_MOBILE_API_KEY}
    usagePlan: {}

functions:
  squad:
    handler: src/index.squad
    events:
      - http:
          method: GET
          path: /squad
          private: true
  market:
    handler: src/index.market
    events:
      - http:
          method: GET
          path: /market
          private: true
  myMarketListings:
    handler: src/index.myMarketListings
    events:
      - http:
          method: GET
          path: /market/my-listings
          private: true
  playerOffers:
    handler: src/index.playerOffers
    events:
      - http:
          method: GET
          path: /market/offers
          private: true
  rejectPlayerOffer:
    handler: src/index.rejectPlayerOffer
    events:
      - http:
          method: PUT
          path: /market/offers/{offerId}
          private: true
  acceptPlayerOffer:
    handler: src/index.acceptPlayerOffer
    events:
      - http:
          method: PUT
          path: /market/offers/{offerId}/accept
          private: true
  unlistPlayer:
    handler: src/index.unlistPlayer
    events:
      - http:
          method: DELETE
          path: /market/my-listings/{playerId}
          private: true
  listPlayer:
    handler: src/index.listPlayer
    events:
      - http:
          method: POST
          path: /market/my-listings/{playerId}
          private: true
  playerBids:
    handler: src/index.playerBids
    events:
      - http:
          method: GET
          path: /market/my-bids
          private: true
  lineup:
    handler: src/index.lineup
    events:
      - http:
          method: GET
          path: /lineup
          private: true
  saveLineup:
    handler: src/index.saveLineup
    events:
      - http:
          method: PUT
          path: /lineup
          private: true
  priceHistory:
    handler: src/index.priceHistory
    events:
      - http:
          method: GET
          path: /players/{playerId}/price-history
          private: true
  performanceHistory:
    handler: src/index.performanceHistory
    events:
      - http:
          method: GET
          path: /players/{playerId}/performance-history
          private: true
  matchDayDetails:
    handler: src/index.matchDayDetails
    events:
      - http:
          method: GET
          path: /players/{playerId}/match-day-details
          private: true
